project:
  type: website
  output-dir: docs
  resources: 
    - files
    - images

website:
  title: "**Corey Michaud**"
  site-url: https://coreymichaud.github.io
  description: "Corey Michaud's Portfolio"
  favicon: images/stats.png
  open-graph: true
  google-analytics: "G-843MGSESNK"
  cookie-consent: 
    style: headline
  drafts:
    - blog/AI-Art-Ethics/index.qmd
    - blog/Lets-Talk-Metrics/index.qmd
  
  navbar:
    search: true
    tools-collapse: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
        
    tools:
      - icon: github
        href: https://github.com/coreymichaud
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/coreymichaud1/
        target: _blank
      - icon: envelope-fill
        href: mailto:cor3y.michaud@gmail.com
        
  page-footer: 
    left: "© Copyright 2024, Corey Michaud"
    right: This website is built with <i class="fa-solid fa-heart"></i>, [<i class="fa-brands fa-github"></i>](https://github.com/coreymichaud/coreymichaud.github.io){target=_blank}, [<i class="fa-brands fa-r-project"></i>](https://www.r-project.org/about.html){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    theme: styles.scss
    include-in-header: head.html
    toc: true
    code-block-style: "bs5"
    highlight-style: "monokai"
    mainfont: "helvetica"
    execute:
      warning: false
      message: false


execute:
  freeze: auto

editor: visual

