project:
  type: website
  output-dir: docs
  resources: 
    - files
    - images

website:
  title: "**Corey Michaud**"
  favicon: images/stats.png
  
  navbar:
    search: true
    tools-collapse: true
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: blog.qmd
        text: Blog
        
    tools:
      - icon: github
        href: https://github.com/coreymichaud
      - icon: linkedin
        href: https://www.linkedin.com/in/coreymichaud1/
      - icon: envelope
        href: mailto:cor3y.michaud@gmail.com
        
  page-footer: 
    left: "© Copyright 2024, Corey Michaud"
    right: This website is built with <i class="fa-solid fa-heart"></i>, [<i class="fa-brands fa-github"></i>](https://github.com/coreymichaud/coreymichaud.github.io){target=_blank}, [<i class="fa-brands fa-r-project"></i>](https://www.r-project.org/about.html){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    css: styles.css
    theme: theme.scss
    toc: true
    code-block-style: "bs5"
    highlight-style: "monokai"
    
execute:
  freeze: true

editor: visual

