{
  "hash": "cb5a511d04915cf2603cc2fe2b1b8431",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Los Angeles Crime Visualized\" # Blog post title\ndescription: \"Visualization of crime in LA with R and ggplot2.\" # Blog post description\ndate: 07-11-2024 # Date this post is published\ncategories: [R, Visualization] # Self-defined categories\nimage: \"/projects/thumbnails/R.png\" # This is the image that will be the preview image and it HAS to be in this file to work\n---\n\n\n\n\n\n<!-- This is the github button -->\n\n<a href=\"https://github.com/coreymichaud/LA-Crime-Visualized\" class=\"btn\" target=\"_blank\"><i class=\"fab fa-github\"></i> Source Code</a>\n\nThe data in this notebook was taken from https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8 and consists of crime data from Los Angeles, CA (2020-2024).\n\nAll visualizations, statistics, and insights discussed are based on this dataset and time frame mentioned above only. The objective is to gain a comprehensive understanding of crime in Los Angeles through data exploration and visualization.\n\nThe source code button above shows when I uploaded the data to GitHub in 2023, but as of 2024 this is the more updated version.\n\n# Loading Libraries\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Libraries\nlibrary(tidyverse)\nlibrary(lubridate)\n```\n:::\n\n\n\n\n\n# Exploratory Data Analysis\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing dataset\ncrime <- read.csv(\"crime.csv\")\nhead(crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      DR_NO              Date.Rptd               DATE.OCC TIME.OCC AREA\n1 190326475 03/01/2020 12:00:00 AM 03/01/2020 12:00:00 AM     2130    7\n2 200106753 02/09/2020 12:00:00 AM 02/08/2020 12:00:00 AM     1800    1\n3 200320258 11/11/2020 12:00:00 AM 11/04/2020 12:00:00 AM     1700    3\n4 200907217 05/10/2023 12:00:00 AM 03/10/2020 12:00:00 AM     2037    9\n5 220614831 08/18/2022 12:00:00 AM 08/17/2020 12:00:00 AM     1200    6\n6 231808869 04/04/2023 12:00:00 AM 12/01/2020 12:00:00 AM     2300   18\n  AREA.NAME Rpt.Dist.No Part.1.2 Crm.Cd\n1  Wilshire         784        1    510\n2   Central         182        1    330\n3 Southwest         356        1    480\n4  Van Nuys         964        1    343\n5 Hollywood         666        2    354\n6 Southeast        1826        2    354\n                               Crm.Cd.Desc             Mocodes Vict.Age\n1                         VEHICLE - STOLEN                            0\n2                    BURGLARY FROM VEHICLE      1822 1402 0344       47\n3                            BIKE - STOLEN           0344 1251       19\n4 SHOPLIFTING-GRAND THEFT ($950.01 & OVER)           0325 1501       19\n5                        THEFT OF IDENTITY 1822 1501 0930 2004       28\n6                        THEFT OF IDENTITY 1822 0100 0930 0929       41\n  Vict.Sex Vict.Descent Premis.Cd                                  Premis.Desc\n1        M            O       101                                       STREET\n2        M            O       128            BUS STOP/LAYOVER (ALSO QUERY 124)\n3        X            X       502 MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)\n4        M            O       405                               CLOTHING STORE\n5        M            H       102                                     SIDEWALK\n6        M            H       501                       SINGLE FAMILY DWELLING\n  Weapon.Used.Cd Weapon.Desc Status  Status.Desc Crm.Cd.1 Crm.Cd.2 Crm.Cd.3\n1             NA                 AA Adult Arrest      510      998       NA\n2             NA                 IC  Invest Cont      330      998       NA\n3             NA                 IC  Invest Cont      480       NA       NA\n4             NA                 IC  Invest Cont      343       NA       NA\n5             NA                 IC  Invest Cont      354       NA       NA\n6             NA                 IC  Invest Cont      354       NA       NA\n  Crm.Cd.4                                 LOCATION Cross.Street     LAT\n1       NA  1900 S  LONGWOOD                     AV              34.0375\n2       NA  1000 S  FLOWER                       ST              34.0444\n3       NA  1400 W  37TH                         ST              34.0210\n4       NA 14000    RIVERSIDE                    DR              34.1576\n5       NA                        1900    TRANSIENT              34.0944\n6       NA  9900    COMPTON                      AV              33.9467\n        LON\n1 -118.3506\n2 -118.2628\n3 -118.3002\n4 -118.4387\n5 -118.3277\n6 -118.2463\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Changing Date.Rptd and DATE.OCC to date format\ncrime$Date.Rptd <- as.Date(crime$Date.Rptd, format = \"%m/%d/%Y\")\ncrime$DATE.OCC <- as.Date(crime$DATE.OCC, format = \"%m/%d/%Y\")\n\n\ntimes_char <- sprintf(\"%04d\", crime$TIME.OCC)\ndatetime <- strptime(times_char, format = \"%H%M\")\ncrime$TIME.OCC <- format(datetime, format = \"%H:%M\")\n\nhead(crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      DR_NO  Date.Rptd   DATE.OCC TIME.OCC AREA AREA.NAME Rpt.Dist.No Part.1.2\n1 190326475 2020-03-01 2020-03-01    21:30    7  Wilshire         784        1\n2 200106753 2020-02-09 2020-02-08    18:00    1   Central         182        1\n3 200320258 2020-11-11 2020-11-04    17:00    3 Southwest         356        1\n4 200907217 2023-05-10 2020-03-10    20:37    9  Van Nuys         964        1\n5 220614831 2022-08-18 2020-08-17    12:00    6 Hollywood         666        2\n6 231808869 2023-04-04 2020-12-01    23:00   18 Southeast        1826        2\n  Crm.Cd                              Crm.Cd.Desc             Mocodes Vict.Age\n1    510                         VEHICLE - STOLEN                            0\n2    330                    BURGLARY FROM VEHICLE      1822 1402 0344       47\n3    480                            BIKE - STOLEN           0344 1251       19\n4    343 SHOPLIFTING-GRAND THEFT ($950.01 & OVER)           0325 1501       19\n5    354                        THEFT OF IDENTITY 1822 1501 0930 2004       28\n6    354                        THEFT OF IDENTITY 1822 0100 0930 0929       41\n  Vict.Sex Vict.Descent Premis.Cd                                  Premis.Desc\n1        M            O       101                                       STREET\n2        M            O       128            BUS STOP/LAYOVER (ALSO QUERY 124)\n3        X            X       502 MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)\n4        M            O       405                               CLOTHING STORE\n5        M            H       102                                     SIDEWALK\n6        M            H       501                       SINGLE FAMILY DWELLING\n  Weapon.Used.Cd Weapon.Desc Status  Status.Desc Crm.Cd.1 Crm.Cd.2 Crm.Cd.3\n1             NA                 AA Adult Arrest      510      998       NA\n2             NA                 IC  Invest Cont      330      998       NA\n3             NA                 IC  Invest Cont      480       NA       NA\n4             NA                 IC  Invest Cont      343       NA       NA\n5             NA                 IC  Invest Cont      354       NA       NA\n6             NA                 IC  Invest Cont      354       NA       NA\n  Crm.Cd.4                                 LOCATION Cross.Street     LAT\n1       NA  1900 S  LONGWOOD                     AV              34.0375\n2       NA  1000 S  FLOWER                       ST              34.0444\n3       NA  1400 W  37TH                         ST              34.0210\n4       NA 14000    RIVERSIDE                    DR              34.1576\n5       NA                        1900    TRANSIENT              34.0944\n6       NA  9900    COMPTON                      AV              33.9467\n        LON\n1 -118.3506\n2 -118.2628\n3 -118.3002\n4 -118.4387\n5 -118.3277\n6 -118.2463\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding dimension of crime dataset\ndim(crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 959241     28\n```\n\n\n:::\n:::\n\n\n\n\nThis dataset has 959,241 rows and 28 columns.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Applying NA function to each column\ncrime_is_na <- sapply(crime, function(x) sum(is.na(x)))\ncrime_is_na[which(crime_is_na > 0)]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     Premis.Cd Weapon.Used.Cd       Crm.Cd.1       Crm.Cd.2       Crm.Cd.3 \n            13         634058             11         890716         956944 \n      Crm.Cd.4 \n        959177 \n```\n\n\n:::\n:::\n\n\n\n\nPremis.Cd has some missing values. Weapon.Used.Cd has so many missing values because not all recorded crimes involve a weapon, and Crm.Cd.2-4 have many missing values because they will only have a value if more than 1 crime was committed in the same instance. I will not be removing any rows that contain missing values because if I do, there will not be nearly as much data. As a result, I will account for missing values during statistical tests.\n\n### What are the different types of crimes recorded?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding length of crime list\nlength(table(crime$Crm.Cd.Desc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 139\n```\n\n\n:::\n:::\n\n\n\n\nThere are 139 different types of crimes that have been committed.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sorting the number of occurrences for each crime\nsorted_crimes <- table(crime$Crm.Cd.Desc) %>% sort(decreasing = TRUE)\n```\n:::\n\n\n\n\nThere are too many crimes to print out the name of each one, but if you'd like you can download this rmd and print the sorted_crimes variable.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(sorted_crimes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n                                       VEHICLE - STOLEN \n                                                 105537 \n                               BATTERY - SIMPLE ASSAULT \n                                                  74596 \n                                  BURGLARY FROM VEHICLE \n                                                  59476 \n                                      THEFT OF IDENTITY \n                                                  59327 \nVANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS) \n                                                  58180 \n                                               BURGLARY \n                                                  57597 \n```\n\n\n:::\n:::\n\n\n\n\nHere are the 5 highest occurring crimes.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(sorted_crimes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n      INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES) \n                                                 6 \n                     THEFT, COIN MACHINE - ATTEMPT \n                                                 6 \nFIREARMS EMERGENCY PROTECTIVE ORDER (FIREARMS EPO) \n                                                 5 \n                DISHONEST EMPLOYEE ATTEMPTED THEFT \n                                                 4 \n          FIREARMS RESTRAINING ORDER (FIREARMS RO) \n                                                 4 \n                                    TRAIN WRECKING \n                                                 1 \n```\n\n\n:::\n:::\n\n\n\n\nHere are the 5 lowest occurring crimes.\n\n### How many of the crimes were only attempted?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding number of crimes with \"ATTEMPT\" in title\nsum(grepl(\"ATTEMPT\", crime$Crm.Cd.Desc, ignore.case = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15716\n```\n\n\n:::\n:::\n\n\n\n\nOut of all the crimes committed, 15,716 of them were attempts.\n\n### How many crimes involved stolen property?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding number of crimes with \"STOLEN\" in title\nsum(grepl(\"STOLEN\", crime$Crm.Cd.Desc, ignore.case = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 122940\n```\n\n\n:::\n:::\n\n\n\n\nOut of all the crimes committed, 122,940 of them involved stolen property.\n\n### Which days had the most amount of crime? The least?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sorting dates of crimes based on how many occurred that day\ndate_occ_counts <- crime %>% count(DATE.OCC) %>% arrange(desc(n))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(date_occ_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    DATE.OCC    n\n1 2020-01-01 1149\n2 2023-01-01 1137\n3 2022-12-02 1132\n4 2023-02-01 1090\n5 2022-10-01 1077\n6 2022-12-01 1056\n```\n\n\n:::\n:::\n\n\n\n\nThe date with the most amount of crime is 01/01/2020 with 1149 instances.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntail(date_occ_counts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       DATE.OCC   n\n1646 2024-07-03 189\n1647 2024-07-05 172\n1648 2024-07-04 171\n1649 2024-07-06 170\n1650 2024-07-07 121\n1651 2024-07-08  48\n```\n\n\n:::\n:::\n\n\n\n\nThe date with the least amount of crime is 07/08/2024 with 48 instances.\n\n# Graphing the Data and Conducting Statistical Analysis\n\n### Which areas had the most amount of crime? The least?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_name_counts <- crime %>% count(AREA.NAME) %>% arrange(desc(n))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(head(area_name_counts, 7), aes(x = fct_inorder(AREA.NAME), y = n, fill = fct_inorder(AREA.NAME))) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = n), vjust = -0.5) +\n  labs(x = \"Area\", y = \"# of Crimes Comitted\", title = \"Areas with the Highest Number of Crimes Comitted\") +\n  theme(plot.title = element_text(hjust = 0.5), legend.position = \"none\") +\n  scale_y_continuous(limits = c(0, 60000))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\nThe area with the highest amount of crime is77th Street with 59,889 reported cases.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tail(area_name_counts, 7), aes(x = fct_inorder(AREA.NAME), y = n, fill = fct_inorder(AREA.NAME))) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = n), vjust = -0.5) +\n  labs(x = \"Area\", y = \"# of Crimes Comitted\", title = \"Areas with the Lowest Number of Crimes Comitted\") +\n  theme(plot.title = element_text(hjust = 0.5), legend.position = \"none\") +\n  scale_y_continuous(limits = c(0, 40000))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\nThe area with the lowest amount of crime is Foothill with 31,928 reported cases.\n\n### What premise had a crime occur the most? The least?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npremise_counts <- crime %>% count(Premis.Desc) %>% arrange(desc(n))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(head(premise_counts, 7), aes(x = fct_inorder(Premis.Desc), y = n, fill = fct_inorder(Premis.Desc))) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = n), vjust = -0.5, size = 3) +\n  labs(x = \"Premise\", y = \"# of Crimes\", title = \"Premise Where Crime Occured the Most\") +\n  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.ticks.x = element_blank()) +\n  scale_y_continuous(limits = c(0, 220000)) +\n  guides(fill = guide_legend(title = \"Legend\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\nThe premise where the most crime occurs are single family dwellings.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tail(premise_counts, 7), aes(x = fct_inorder(Premis.Desc), y = n, fill = fct_inorder(Premis.Desc))) +\n  geom_bar(stat = \"identity\") +\n  geom_text(aes(label = n), vjust = -0.5, size = 3) +\n  labs(x = \"Premise\", y = \"# of Crimes\", title = \"Premise Where Crime Occured the Least\") +\n  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_blank(), axis.ticks.x = element_blank()) +\n  scale_y_continuous(limits = c(0, 2.2)) +\n  guides(fill = guide_legend(title = \"Legend\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\nThe premise where the least crime occurs are trams/streetcars.\n\n### Show the number of crimes commited per age of victim\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrime_per_age <- table(crime$Vict.Age)[5:103] %>% as.data.frame()\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crime_per_age, aes(x = Var1, y = Freq, fill = Var1)) +\n  geom_bar(stat = \"identity\") +\n  labs(x = \"Age of Victim\", y = \"# of Crimes\", title = \"Number of Crimes per Victim Age\") +\n  theme(plot.title = element_text(hjust = 0.5), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 5), legend.position = \"none\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n\nWe can see most victims are aged 19-50, where more children and elderly people are less victimized.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Creating age groups\ncrime_per_age$group <- cut(as.numeric(crime_per_age$Var1), breaks = c(0, 12, 17, 24, 39, 59, 120), labels = c(\"1-12\", \"13-17\", \"18-24\", \"25-39\", \"40-59\", \"60-120\"))\n\n# Finding age group proportions\ncrime_per_age <- crime_per_age %>% group_by(group) %>% mutate(Proportion = Freq / sum(Freq))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crime_per_age, aes(x = group, y = Proportion, fill = group)) +\n  geom_violin() +\n  stat_summary(fun = median, geom=\"point\", size=2, color=\"red\") +\n  labs(x = \"Age Group\", y = \"Proportion\", title = \"Distribution of Crime Proportions by Age Group\") + \n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\nFrom the violin chart, we can see the age group with the highest number of victims is 13-17. The red dots, representing the median, show  the 13-17 age group takes up about 20% of the data. The lowest proportion group is the 60-120 year old group, likely due to the older individuals having less chance to become victim of a crime and it is skewed. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(crime[crime$Vict.Age > 0,], aes(x = Vict.Age)) +\n  geom_boxplot(fill = \"green\") +\n  labs(x = \"Age\", title = \"Victim Age\") +\n  theme(plot.title = element_text(hjust = 0.5))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\nMedian age of victim seems to be around 37 years old with an IQR of approximately 28-50 years old.\n\n### How many crimes occured with a weapon or force?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finding number of crimes committed with a weapon\ncrime_weapon_na_count <- sum(is.na(crime$Weapon.Used.Cd))\ncrime_weapon_count <- 788767 - crime_weapon_na_count\n\nweapons <- data.frame(\n  Weapon = c(\"Yes\", \"No\"),\n  cc = c(crime_weapon_count, crime_weapon_na_count)\n)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(weapons, aes(x = Weapon, y = cc, fill = Weapon)) +\n  geom_bar(stat = \"identity\") +\n  labs(x = \"Weapon\", y = \"Counts\", title = \"How Many Crimes Were Committed With A Weapon?\") +\n  theme(plot.title = element_text(hjust = 0.5)) +\n  scale_y_continuous(labels = scales::comma)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n\n\nWe can see there's less crimes committed with a weapon than without one, more than a third less.\n\n### Is there a difference in the proportion of women who are victim of a crime to men?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmale_victims <- subset(crime, Vict.Sex == \"M\")\nfemale_victims <- subset(crime, Vict.Sex == \"F\")\n\nprop.test(\n  x = c(nrow(female_victims), nrow(male_victims)),\n  n = c(788767,788767)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions with continuity correction\n\ndata:  c(nrow(female_victims), nrow(male_victims)) out of c(788767, 788767)\nX-squared = 4590.5, df = 1, p-value < 2.2e-16\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.05538834 -0.05227591\nsample estimates:\n   prop 1    prop 2 \n0.4407461 0.4945782 \n```\n\n\n:::\n:::\n\n\n\n\nWith a p-value close to 0 and an alpha level of 0.05, we can reject the null hypothesis and state that the true proportion of victims of a crime who are woman or who are men are different.\n\n### Are woman victims of certain crimes more often than men?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngender_crime <- subset(crime, Vict.Sex == \"M\" | Vict.Sex == \"F\")\n\n# Using Chi-Square test of Independence\nchisq.test(table(gender_crime$Vict.Sex, gender_crime$Crm.Cd.Desc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(gender_crime$Vict.Sex, gender_crime$Crm.Cd.Desc)\nX-squared = 75535, df = 136, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nWith a p-value close to 0 and an alpha level of 0.05, we can reject the null hypothesis, indicating a statistically significant association between gender and crime type on an individual.\n\n### What premise had the most vandalisms? The least?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Counting number of vandalism reports at each premise\npremise_vandalisms <- crime %>% filter(grepl(\"VANDALISM\", Crm.Cd.Desc, ignore.case = TRUE)) %>% group_by(Premis.Desc) %>% summarize(Count = n()) %>% arrange(desc(Count))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(head(premise_vandalisms, 10), aes(x = fct_inorder(Premis.Desc), y = Count)) +\n  geom_segment(aes(x = fct_inorder(Premis.Desc), xend = Premis.Desc, y = 0, yend = Count)) +\n  geom_point(color = \"orange\", size = 4) +\n  coord_flip() +\n  labs(x = \"Premise\", y = \"Count\", title = \"Most # of Vandalisms at Premises in LA\") +\n  theme_light() +\n  theme(axis.text.y = element_text(size = 6), plot.title = element_text(hjust = 0.5), \n        panel.grid.major.x = element_blank(), panel.border = element_blank(), \n        plot.margin = margin(c(10,20,10,10), unit = \"pt\")\n        )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\nThe premise with the highest number of reported vandalism are vehicles (passenger/trucks).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(tail(premise_vandalisms, 10), aes(x = fct_inorder(Premis.Desc), y = Count)) +\n  geom_segment(aes(x = fct_inorder(Premis.Desc), xend = Premis.Desc, y = 0, yend = Count)) +\n  geom_point(color = \"orange\", size = 4) +\n  coord_flip() +\n  labs(x = \"Premise\", y = \"Count\", title = \"Most # of Vandalisms at Premises in LA\") +\n  theme_light() +\n  theme(axis.text.y = element_text(size = 6), plot.title = element_text(hjust = 0.5), \n        panel.grid.major.x = element_blank(), panel.border = element_blank(), \n        plot.margin = margin(c(10,20,10,10), unit = \"pt\")\n        )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\nSome MTA lines have the lowest number of vandalisms, with only 1 recorded, as well as a skating rink and tool shed having only 1 instance. In fact, there's many more which only have 1 reported vandalism.\n\n### What percent of crimes are still being investigated?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(grepl(\"Cont\", crime$Status.Desc, ignore.case = TRUE)) / nrow(crime)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7979997\n```\n\n\n:::\n:::\n\n\n\n\n79.80% of crimes are still being investigated.\n\n### Are certain ethnic groups victims of crimes more often than others?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndescent_table <- table(crime$Vict.Descent)[3:21]\nprob = rep(1/length(descent_table), length(descent_table))\n\nchisq.test(descent_table, p = prob)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  descent_table\nX-squared = 2713681, df = 18, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\nWith a p-value is close to 0, and alpha = 0.5, we can reject the null and state that ethnic groups are not equally as likely to be targeted for a crime.\n\n### Are there any seasons where crime is more frequent? Less frequent?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping the date and number of crimes\ndaily_crime <- crime %>% group_by(DATE.OCC) %>% summarize(Count = n())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(daily_crime, aes(x = DATE.OCC, y = Count)) +\n    geom_line() +\n    facet_wrap(~ year(DATE.OCC), ncol = 3, nrow = 2, scales = \"free\") +\n    labs(x = \"Time\", title = \"Crime over Time\") +\n    theme(plot.title = element_text(hjust = 0.5)) +\n    scale_x_date(date_breaks = \"1 month\", date_labels = \"%b\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-36-1.png){width=672}\n:::\n:::\n\n\n\n\nIt seems like the beginning of each month there's a spike in crime where the biggest spike is in January.\n\n### Is there a certain month that has more crime yearly than others?\n\nIf we take a look at crime from the graph above, we can see that there's not really a specific month that generally has more or less crime than others.\n\n### Has crime increased over time in any area?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Grouping the top 12 areas by date and number of crimes\nselected <- area_name_counts[1:12,1]\nfiltered_crime <- crime %>% filter(AREA.NAME %in% selected)\ncrime_time_area <- filtered_crime %>% group_by(DATE.OCC, AREA.NAME) %>% summarize(Count = n())\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n  ggplot(crime_time_area, aes(x = DATE.OCC, y = Count)) +\n    geom_line() +\n    facet_wrap(~ AREA.NAME, scales = \"free\") +\n    labs(x = \"Time\", title = \"Crime over Time\") +\n    theme(plot.title = element_text(hjust = 0.5)) +\n    stat_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\n\n\nNo area seems to have a significant increase in crime over time, but some areas like Central, Newton, Olympic, Pacific, and West LA do have some increase in crime. The areas all seem to have some major spikes in crime on certain days, but nothing that overlaps with each other.\n\n### Are there certain times of the day where crime occurs more? What about day vs night?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert military time to hours and minutes\nhours <- as.numeric(substr(crime$TIME.OCC, 1, 2))\nminutes <- as.numeric(substr(crime$TIME.OCC, 4, 5))\n\n# Calculate the intervals\ninterval <- sprintf(\"%02d:%02d\", floor((hours * 60 + minutes) %/% 30 / 2), ((hours * 60 + minutes) %/% 30 %% 2) * 30)\ninterval_df <- as.data.frame(table(interval))\n\nnumber_of_bar <- nrow(interval_df)\nangle <- 90 - 360 * (as.numeric(interval_df$interval) - 0.5) / number_of_bar\n\ninterval_df$angle<-ifelse(angle < -90, angle + 180, angle)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot of crime frequency per 30 minutes\nggplot(interval_df, aes(x = as.factor(interval), y = Freq, fill = Freq)) +\n  geom_bar(stat = \"identity\", alpha = 0.7) +\n  geom_text(aes(x = interval, y = Freq, label = interval, hjust = 0), \n            color = \"black\", fontface = \"bold\", alpha = 0.6, size = 2, angle = angle, \n            inherit.aes = FALSE) +\n  scale_fill_gradient(low = \"green\", high = \"red\") +\n  theme_minimal() +\n  theme(\n    axis.text = element_blank(),\n    panel.grid = element_blank(),\n    axis.title = element_blank(),\n    plot.margin = unit(rep(-0.5, 4), \"cm\")\n  ) +\n  coord_polar(start = 0) +\n  scale_y_continuous(limits = c(-30000, 40000))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-40-1.png){width=672}\n:::\n:::\n\n\n\n\nWe can see that as the time of day increases, the frequency of crime increases, but there is a major spike at noon (12:00).\n\nIf you've made it to the end thank you! I am trying to upload projects using Quarto and I'm still getting used to everything, so I hope to make this prettier eventually!",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}